In [1]:
import numpy as np

# Exercise 1

In [3]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr1_reshape=arr1.reshape(2,5)
arr1_reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Exercise 2

In [7]:
arr2=np.array([1,2,3,5,7,9,10,20,16,14,12,6,4,2,8])

In [9]:
arr2[5:15]

array([ 9, 10, 20, 16, 14, 12,  6,  4,  2,  8])

# Exercise 3

In [11]:
import pandas as pd

In [13]:
fruits=pd.Series({'apple':3,'bananas':2,'oranges':1})
fruits

apple      3
bananas    2
oranges    1
dtype: int64

In [15]:
fruits['pears']=4

In [17]:
fruits

apple      3
bananas    2
oranges    1
pears      4
dtype: int64

# Exercise 4

In [43]:
data={
    'Name':['Alice','Bob','Charlie','Lucky','Adhil','Anusha','Summayya','Riswan','Nihal','Anas'],
    'Age':[20,21,22,23,24,25,26,27,28,29],
    'Gender':['M','M','M','M','M','F','F','M','M','M']}
data

{'Name': ['Alice',
  'Bob',
  'Charlie',
  'Lucky',
  'Adhil',
  'Anusha',
  'Summayya',
  'Riswan',
  'Nihal',
  'Anas'],
 'Age': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 'Gender': ['M', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'M', 'M']}

In [45]:
df=pd.DataFrame(data)
df

       Name  Age Gender
0     Alice   20      M
1       Bob   21      M
2   Charlie   22      M
3     Lucky   23      M
4     Adhil   24      M
5    Anusha   25      F
6  Summayya   26      F
7    Riswan   27      M
8     Nihal   28      M
9      Anas   29      M

# Exercise 5

In [51]:
df['Occupation']=['Programmer','Manager','Manager','Analyst','Programmer','Manager','Analyst','Manager','Analyst','Programmer']

In [53]:
df

       Name  Age Gender  Occupation
0     Alice   20      M  Programmer
1       Bob   21      M     Manager
2   Charlie   22      M     Manager
3     Lucky   23      M     Analyst
4     Adhil   24      M  Programmer
5    Anusha   25      F     Manager
6  Summayya   26      F     Analyst
7    Riswan   27      M     Manager
8     Nihal   28      M     Analyst
9      Anas   29      M  Programmer

# Exercise 6

In [57]:
df[df.Age>=25]

       Name  Age Gender  Occupation
5    Anusha   25      F     Manager
6  Summayya   26      F     Analyst
7    Riswan   27      M     Manager
8     Nihal   28      M     Analyst
9      Anas   29      M  Programmer

# Exercise 7

In [63]:
dd=pd.read_csv("C:\\Users\\thask\\OneDrive\\Documents\\data.csv")
df

       Name  Age Gender  Occupation
0     Alice   20      M  Programmer
1       Bob   21      M     Manager
2   Charlie   22      M     Manager
3     Lucky   23      M     Analyst
4     Adhil   24      M  Programmer
5    Anusha   25      F     Manager
6  Summayya   26      F     Analyst
7    Riswan   27      M     Manager
8     Nihal   28      M     Analyst
9      Anas   29      M  Programmer